// SPDX-License-Identifier: MIT
pragma solidity 0.8.17;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";
import "@openzeppelin/contracts/access/Ownable.sol";

contract autoGeneratedNFT is ERC721, Ownable {

    constructor() ERC721("MyToken", "MTK") {}

    uint tokenId = 1;
    address public _upKeepAddress;

    function safeMint(address to) public onlyChainlink {
        _safeMint(to, tokenId);
        tokenId++;
    }

    function upKeepAddress(address upKeep) public onlyOwner{
        _upKeepAddress = upKeep;
    }

    modifier onlyChainlink(){
        require(msg.sender == _upKeepAddress || msg.sender == owner(), "Invalid User");
        _;
    }
}